# Create full conda environment for development, including some useful tools
name: awips-docs
channels:
  - conda-forge
dependencies:
  - python=2.7
  - pip
  - pip:
    - mkdocs-unidata
    - fontawesome_markdown
